### ISSUE TITLE
View Menu

### ISSUE THREAD

**Issue by JWGreenstone** [SiliconStudio/paradox#182]
When I close things such as the Asset Preview window (or any of them), I cannot bring them back. Even using the View Menu, the item is checked, but nothing shows.

-Restarting Paradox will bring back Asset View, Solution Explorer, References
-Nothing I do will bring back Asset Preview, it has vanished from the universe completely.

Windows 7 64bit
Dell Inspiron 17R laptop

**Comment by JWGreenstone** [comment]
Update:
-Restarting the computer did not bring it back
-Uninstalling Paradox and reinstalling did not bring it back

**Comment by Benlitz** [comment]
Sorry about that, this issue has been fixed in one of our development branchs that has not been merged yet in the public release.

We'll try to fix this soon, in the meantime you can delete the file C:\Users\(YourProfile)\AppData\Roaming\Silicon Studio Corp\Paradox\GameStudioInternal.conf
Or alternatively you can edit it and remove the entry related to the docking layout.

**Comment by JWGreenstone** [comment]
Perfect, thanks! I'm really liking what I see in this engine so far.

**Comment by Benlitz** [comment]
Should be fixed in 1.1.0
