### ISSUE TITLE
console (logging) window doesn't appear when debugging

### ISSUE THREAD

**Issue by jmkinzer** [SiliconStudio/paradox#192]
Using the logging mechanism in SiliconStudio.Core.Diagnostics:
Log.Log(new LogMessage("foo", LogMessageType.Info, s));

This causes the console to appear when running normally however running under the debugger (Debug / Start Debugging) it fails to appear.

**Comment by gitfool** [comment]
Looks like this behavior is by design ([ConsoleLogListener.cs#L49](https://github.com/SiliconStudio/paradox/blob/master/sources/common/core/SiliconStudio.Core/Diagnostics/ConsoleLogListener.cs#L49)).

The message should appear in the Visual Studio output window ([ConsoleLogListener.cs#L126](https://github.com/SiliconStudio/paradox/blob/master/sources/common/core/SiliconStudio.Core/Diagnostics/ConsoleLogListener.cs#L126)).

**Comment by jmkinzer** [comment]
Thanks, I missed that.
