### ISSUE TITLE
Can't open the Materials sample of 1.1b

### ISSUE THREAD

**Issue by HugoPeters** [SiliconStudio/paradox#207]
Hello,

I'm having trouble creating a new "Materials" example project.
Paradox keeps throwing an error about the application being in a "corrupted state".
Here's a screenshot of the log: http://i.imgur.com/vadCdho.png

So far this only happened with the Materials template. The Procedural Models one loads & runs just fine.

**Comment by xen2** [comment]
I can't seem to be able to reproduce the problem.

**Comment by xen2** [comment]
I think I might know the issue. It happens only when there is Paradox 1.0 still installed.

Projects created starting from 1.1 includes a .props file alongside the .pdxpkg to let know which Paradox to target, but it seems it is missing for this sample (actually it was fixed on our side but forgot to update superproject submodule for our final release build).

As a workaround, you can either remove Paradox 1.0, or simply create that .props file (just check how it is for other project).

It will be fixed in next release, thanks.

**Comment by xen2** [comment]
Seems to be different. Removing and reinstalling Paradox doesn't help?

**Comment by HugoPeters** [comment]
Sorry for the late response. For some reason the problem seems to have auto-resolved itself. Thanks anyways!
