### ISSUE TITLE
Serialization issue

### ISSUE THREAD

**Issue by AlistairClark7** [SiliconStudio/paradox#228]
I get the following error when trying to compile:

`Error	23	The command ""C:\Program Files (x86)\Paradox\GamePackages\Paradox.1.1.2-beta\Bin\Windows-Direct3D11\SiliconStudio.Assets.CompilerApp.exe"  --platform=Windows --graphics-platform=Direct3D11 --profile=Windows --project-configuration=Debug --output-path="C:\Users\aclark\Documents\Development\Sellsword\Sellsword\Bin\Windows-Direct3D11\Debug\data" --build-path="C:\Users\aclark\Documents\Development\Sellsword\Sellsword\Sellsword.Windows\..\obj\data" --package-file="C:\Users\aclark\Documents\Development\Sellsword\Sellsword\Sellsword.Windows\..\Sellsword.pdxpkg" --log-pipe=""" exited with code 1.	Sellsword.Windows`

This is caused by having a public field/property that has no empty constructor (i.e. can't be serialized) on an async script. I can upload sources/give you access to a repo if you would like to reproduce.

EDIT: This also happens even if I've got an empty constructor on the object in question. I will investigate more.

**Comment by xenux** [comment]
Hello,

If you don't necessary want to serialize your field/property, you can turn it private/protected/internal or add the 'DataMemberIgnore' attribute on it (and keep your constructors as they are).

if you want to serialize your field/property, the serializer needs a public empty constructor in order to be able to instantiate your field/property. Of course, it is recursive: public fields of the field need to have empty public constructor, and so on.

**Comment by xen2** [comment]
I suppose we should at least display a meaningful error message until we decide the exact behavior we want for those non-serializable fields.

**Comment by AlistairClark7** [comment]
Thanks, it doesn't need serializing. What is the serializing actually used for? Is it so that entities etc. can be assigned in the Paradox editor?

**Comment by xenux** [comment]
Yes, it is so that you can set it from the editor (in the property grid of the entity's script component).

**Comment by jwollen** [comment]
This will be fixed in the next release. There will be only a warning if a member can not be serialized.
