### ISSUE TITLE
Exception on game start, no way to find out whats wrong

### ISSUE THREAD

**Issue by Mylan719** [SiliconStudio/paradox#299]
When I start my game suddendly there is this exception:
"No serializer available for type id fffd9013e80e4097417aa3322cb3dee7 and base type SiliconStudio.Paradox.Engine.Script"
There is no way at all for me to find out what is wrong. The guid is not helping.
Stack trace Points to SceneSystem load, AssetManager.Load<T>(...) ect.

Heppened to me when I forgot [DataMemberIgnore] on public property in scriptfile, but this time, I am sure I have no public members without [DataMemberIgnore]

**Comment by xen2** [comment]
The problem is the script type itself.
Could it be that your script is private somehow?

**Comment by Mylan719** [comment]
By debuging I found out that there is some {Entity Entity} in MemberReuseSerializer.Serialize and script component containing no scripts for which EnsureEntity has trown exception on my callstack

**Comment by Mylan719** [comment]
Both scripts I have are public, I found out just now they were in wrong namespace (it differed from namespace for project .Game), I corrected the namespace, rebuild, restarted paradox, chose scripts once again, but it still fails.
How do I know for which objecy the serialize function failed?

**Comment by xen2** [comment]
If easy to reproduce in a simple project, could you do it and send it to us please?

**Comment by Mylan719** [comment]
Sure. This is the project as it was, It has just few clases, so should not be much of a trouble. Plus you can easily try wiping .Game project and adding new script and see it does not work either.
https://onedrive.live.com/redir?resid=DA75415232937F7B!1778&authkey=!AGewWGpAzCWtBn4&ithint=file%2czip

**Comment by jwollen** [comment]
The problem here is the reference to the .Core project, which is targeting .Net 4.6, while the .Game is targeting .Net Portable 4.5.1. Visual Studio also outputs a warning about this.

At runtime, the assembly will not be loaded, serializers will not be found and the above error occurs.

To solve this, target the same framework version in .Core and .Game. You can mimic the way .Game.csproj is set up. You can also create new code libraries from the GameStudio, which will have the correct target set.
