### ISSUE TITLE
Game is a 'namespace' but is used like a 'type'

### ISSUE THREAD

**Issue by Syrou** [SiliconStudio/paradox#309]
Hi in the latest 1.3.1-beta binding Source files with Visual Studio 2015 Pro does not seem to work very well. I have a clean installation of both computer and Paradox. I create a new game from the "New project" wizard creates a project, and if I open it with Visual Studio 2015 I can build it.

Now I right click my GAMENAME.Game In Paradox Editor (the group that has a # in the icon) in the Solution explorer.
And press Create->Script Source Code. Once that is done, and Visual Studio has reloaded all the changes, I suddently can not build anymore and I get the error: 

Game is a 'namespace' but is used like a 'type'

What's going on?

**Comment by xoofx** [comment]
The issue is fixed and we will release a new version soon.

The bug generating this error message is that the created script from the GameStudio contains the namespace Game, conflicting with the Game class. As a workaround, you can edit manually the script created and remove the ".Game"  from the namespace "GameName.Game"

**Comment by xoofx** [comment]
The latest released version 1.3.2 should fix this issue
