### ISSUE TITLE
Issue with EditText Background color

### ISSUE THREAD

**Issue by donnyv** [SiliconStudio/paradox#331]
Setting the BackgroundColor only seems to change the border but not the actual background of the EditText box.

**Comment by xenux** [comment]
Hi donnyv,

The BackgroundColor is a common property to all the UI Elements. It specifies the background color (the color behind the control design) of the element. It is used mostly for debug in order to be able to visualize the exact space taken by the control in the layout. 
If you want to change the color of a given part of the edit text design, you should change the "ActiveImage", "InactiveImage", "MouseOverImage" images accordingly. Another possibility is to use your own renderer to render the edit text but it is more complex (have a look at UIComponentRenderer and its interface IRendererManager).

**Comment by donnyv** [comment]
So used to desktop development I just assumed it worked the same way.
