### ISSUE TITLE
GUI problem on DPI display

### ISSUE THREAD

**Issue by erikpa1** [SiliconStudio/paradox#587]
Hi I have problems with Xenko gui, i have FullHD *1080* display and my buttons and gui elements are too big, does  someone  know some solution ? :)

**Comment by jwollen** [comment]
Hi!
Could you give us some more details?

- Are you having trouble with editor or in-game GUI?
- Which Windows version are you using?
- Can you add a screenshot?

Thanks!
If you are on Windows 10 you can try to install the latest updates in the meantime.

**Comment by erikpa1** [comment]
Hi, i have latest version I instaled it 2 weeks earlier. The problem is normal problem which have many of programs including photoshop, blender and netbeans, they think they are on 22" display , but I have just 15" normaly it is solved mostly with setting DPI in options, but in xenko i dont see nothing similar
<img width="960" alt="snimka" src="https://cloud.githubusercontent.com/assets/19526670/26097762/e5783ab0-3a25-11e7-96b0-433f0321a918.PNG">

**Comment by Kryptos-FR** [comment]
Which Windows version are you using (please precise the update version)?
What are the DPI settings on your screens?

To me it seems that your DPI settings are incorrect (looks like 150%) for a 15'' screen.

**Comment by erikpa1** [comment]
windows 10, but yeah i have windows on 150% i have to because some applications are too small, and its better for me ,  and here what  i want to find is how  set DPI in xenko on my own

**Comment by Kryptos-FR** [comment]
Then it appears that the Game Studio behaves as expected for a 150% DPI setting.

You can try to disable it on the executable of the Game Studio. Go to `C:\Program Files\Silicon Studio\Xenko\GamePackages\Xenko.2.0.1.1\Bin\Windows` right-click on `Xenko.GameStudio.exe` and try to change the DPI settings in the `Compatibility` tab. Not sure if this will work since basically you are trying to have an application not behave correctly. If not, try to change the settings on the other applications that were too small.
